apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-app-wortner-service-monitor1
  labels:
    release: ms-prometheus
    app: hello-app-wortner
spec:
  endpoints:
  - port: http
    path: '/metrics'
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: hello-app-wortner 
      release: ms-prometheus
