# Default values for network-policy.
# This is a YAML-formatted file.
incomingNetworkPolicy:
  ## Enable creation of Incoming NetworkPolicy resources.
  ##
  enabled: true
  whitelist:
    namespacePurposeLabels:
      - production
      - nginx
    networks:
    # - 10.240.0.0/16
    # Service CIDR
      - 10.0.0.0/16
outgoingNetworkPolicy:
  ## Enable creation of Incoming NetworkPolicy resources.
  enabled: false
  whitelist:
    networks:
    # Service CIDR
     - 10.0.0.0/16